# =========================
# Sustainability
# =========================
/sustainability.do=cocacola.mvc.controller.SustainabilityController
/sustainability/detail=cocacola.mvc.controller.SustainabilityDetailController